in_prefix: 'in/profiles'
out_prefix: 'out'

potential_bias_values: [0.005, 0.01, 0.02, 0.05, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18] # V

number_of_species: 2
reference_concentrations: [1.0e-4, 1.0e-4]  #mM
number_charges: [1, -1]
# potential_bias: 0.1 # V

debye_length: 9.650417803483358e-07 # m

temperature: 298.15  # K
relative_permittivity: 79  # water

height_normalized: 10  # debye lengths

lower_boundary_mesh_size: 0.2  # debye lengths
upper_boundary_mesh_size: 1.0  # debye lengths

line_integral_rolling_mean_window: 500
line_integral_rolling_mean_window_std: 100

# GPR parameters:
# length_scale_values: [10, 1]
# signal_variance_values: [1.e-3, 1.e-2, 0.1, 1]
length_scale_values: [10]
signal_variance_values: [1]
# long_length_scale_values: [50, 100]
# long_signal_variance_values: [1.e-3, 1.e-2, 0.1, 1]
long_length_scale_values: [50]
long_signal_variance_values: [1]

# best combination: 10, 0.01, 50, 0.01
reference_profile_label: rectangle_flat_from_vertical

# surface excess plotting configurations
surface_excess_global:
  hlim: [-0.4, 0.4]
  hticks: [-0.2, 0.0, 0.2]
  ylims:
    - [ -2, -1.65 ]
    - [ 11.5, 14 ]
  yticks:
    - [ -1.74, -1.71, -1.68]
    - [ 11.8, 12, 12.2 ]

surface_excess_global_with_gpr:
  hlim: [ -0.4, 0.4 ]
  hticks: [ -0.2, 0.0, 0.2 ]
  ylims:
    - [ -2, -1.65 ]
    - [ 11.5, 14 ]
  yticks:
    - [ -1.74, -1.71, -1.68 ]
    - [ 11.8, 12, 12.2 ]
    -
surface_excess_local:
  hlim: [ -0.4, 0.4 ]
  hticks: [ -0.2, 0.0, 0.2 ]
  ylims:
    - [ -2, -1.65 ]
    - [ 11.5, 14 ]
  yticks:
    - [ -1.74, -1.71, -1.68 ]
    - [ 11.8, 12, 12.2 ]
    -
surface_excess_local_with_gpr:
  hlim: [ -0.4, 0.4 ]
  hticks: [ -0.2, 0.0, 0.2 ]
  ylims:
    - [ -2, -1.65 ]
    - [ 11.5, 14 ]
  yticks:
    - [ -1.74, -1.71, -1.68 ]
    - [ 11.8, 12, 12.2 ]
    -

unit: um

profiles:
  rectangle_with_single_rough_edge_after_4N_friction_test:
    # profile properties
    file: 1-rough surface after friction test under 4N.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1010
  rectangle_with_single_rough_edge_after_10N_friction_test:
    # profile properties
    file: 3-rough surface after friction test under 10N.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1016
  rectangle_with_single_smooth_edge_after_4N_friction_test:
    file: 2-smooth surface after friction test under 4N.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1010
  rectangle_with_single_smooth_edge_after_10N_friction_test:
    file: 4-smooth surface after friction test under 10N.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1016
  rectangle_with_single_rough_edge_parallel:
    # profile properties
    file: Rough surface-3D-10x2-1-line (Parallel sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1010
  rectangle_with_single_rough_edge_vertical:
    file: Rough surface-3D-10x2-1-line (Vertical sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1007
  rectangle_with_single_smooth_edge_parallel:
    file: Smooth surface-3D-10x2-1-line (Parallel sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1010
  rectangle_with_single_smooth_edge_vertical:
    file: Smooth surface-3D-10x2-1-line (Vertical sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1007
  rectangle_flat_from_parallel:
    file: rectangle_flat_from_parallel.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1010
  rectangle_flat_from_vertical:
    file: rectangle_flat_from_vertical.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1007