in_prefix: 'in/profiles'
out_prefix: 'out'

number_of_species: 2
reference_concentrations: [1.0e-4, 1.0e-4]  #mM
number_charges: [1, -1]
potential_bias: 0.05 # V

debye_length: 9.650417803483358e-07 # m

temperature: 298.15  # K
relative_permittivity: 79  # water

height_normalized: 10  # debye lengths

lower_boundary_mesh_size: 0.2  # debye lengths
upper_boundary_mesh_size: 1.0  # debye lengths

line_integral_rolling_mean_window: 500
line_integral_rolling_mean_window_std: 100

# GPR parameters:
# length_scale_values: [10, 1]
# signal_variance_values: [1.e-3, 1.e-2, 0.1, 1]
length_scale_values: [10]
signal_variance_values: [0.01]
# long_length_scale_values: [50, 100]
# long_signal_variance_values: [1.e-3, 1.e-2, 0.1, 1]
long_length_scale_values: [50]
long_signal_variance_values: [0.01]

# best combination: 10, 0.01, 50, 0.01
reference_profile_label: rectangle_flat_from_vertical

profiles:
  rectangle_with_single_rough_edge_parallel:
    # profile properties
    file: Rough surface-3D-10x2-1-line (Parallel sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1010
    # surface excess plotting configurations
    surface_excess_global:
      hlim: [-0.4, 0.4]
      hticks: [-0.2, 0.0, 0.2]
      ylims:
        - [ -1.6, -1.2 ]
        - [ 3.1, 4.4 ]
      yticks:
        - [ -1.22, -1.26 , -1.3 ]
        - [ 3.2, 3.3, 3.4 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.4, 0.4 ]
      hticks: [ -0.2, 0.0, 0.2 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
  rectangle_with_single_rough_edge_vertical:
    file: Rough surface-3D-10x2-1-line (Vertical sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1007
    # surface excess plotting configurations
    surface_excess_global:
      hlim: [-0.4, 0.4]
      hticks: [-0.2, 0.0, 0.2]
      ylims:
        - [ -1.6, -1.2 ]
        - [ 3.1, 4.4 ]
      yticks:
        - [ -1.22, -1.26 , -1.3]
        - [ 3.2, 3.3, 3.4 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.4, 0.4 ]
      hticks: [ -0.2, 0.0, 0.2 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
  rectangle_with_single_smooth_edge_parallel:
    file: Smooth surface-3D-10x2-1-line (Parallel sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1010
    surface_excess_global:
      hlim: [-0.2, 0.2]
      hticks: [-0.1, 0.0, 0.1]
      ylims:
        - [ -1.26, -1.24 ]
        - [ 3.28, 3.35 ]
      yticks:
        - [ -1.248, -1.245 , -1.242 ]
        - [ 3.285, 3.295, 3.305 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.2, 0.2 ]
      hticks: [ -0.1, 0.0, 0.1 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
  rectangle_with_single_smooth_edge_vertical:
    file: Smooth surface-3D-10x2-1-line (Vertical sliding direction).csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [0,1]
    unpack: true
    max_rows: 1007
    # surface excess plotting configurations
    surface_excess_global:
      hlim: [-0.2, 0.2]
      hticks: [-0.1, 0.0, 0.1]
      ylims:
        - [ -1.26, -1.24 ]
        - [ 3.28, 3.35 ]
      yticks:
        - [ -1.248, -1.245 , -1.242 ]
        - [ 3.285, 3.295, 3.305 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.2, 0.2 ]
      hticks: [ -0.1, 0.0, 0.1 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
  rectangle_flat_from_parallel:
    file: rectangle_flat_from_parallel.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1010
    surface_excess_global:
      hlim: [-0.2, 0.2]
      hticks: [-0.1, 0.0, 0.1]
      ylims:
        - [ -1.26, -1.24 ]
        - [ 3.28, 3.35 ]
      yticks:
        - [ -1.248, -1.246 , -1.244, -1.242 ]
        - [ 3.285, 3.295, 3.305 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.2, 0.2 ]
      hticks: [ -0.1, 0.0, 0.1 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
  rectangle_flat_from_vertical:
    file: rectangle_flat_from_vertical.csv
    xscale: 1.0e-6
    yscale: 1.0e-6
    skiprows: 1
    delimiter: ','
    usecols: [ 0,1 ]
    unpack: true
    max_rows: 1007
    # surface excess plotting configurations
    surface_excess_global:
      hlim: [-0.2, 0.2]
      hticks: [-0.1, 0.0, 0.1]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]
    surface_excess_global_with_gpr:
      hlim: [ -0.2, 0.2 ]
      hticks: [ -0.1, 0.0, 0.1 ]
      ylims:
        - [ -1.2465, -1.2435 ]
        - [ 3.291, 3.299 ]
      yticks:
        - [ -1.246, -1.245, -1.244 ]
        - [ 3.292, 3.294, 3.296, 3.298 ]


