FROM ghcr.io/jorgensd/dolfinx-tutorial:v0.8.0

RUN python3 -m pip install -U jupytext
RUN python3 -m pip install -U adios4dolfinx
RUN python3 -m pip install -U snakemake pulp==2.7.0 
RUN python3 -m pip install -U SurfaceTopography
RUN python3 -m pip install -U git+https://github.com/jotelha/matscipy.git@fenicsx-2d
